version: "2.4"
services:
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    image: prometheus:2.9.2
    network_mode: "host"
    # ports:
    #   - "9090:9090"

  graphite:
    image: graphiteapp/graphite-statsd
    network_mode: "host"
    # ports:
    # - "80:80"
    # - "2003-2004:2003-2004"
    # - "2023-2024:2023-2024"
    # - "8125:8125/udp"
    # - "8126:8126"

  graphite_exporter:
    image: prom/graphite-exporter
    network_mode: "host"
    # ports:
    #   - "9108:9108"
    #   - "9109:9109"
    #   - "9109:9109/udp"

  collectd:
    build:
      context: ./collectd
      dockerfile: Dockerfile
    image: collectd:5.5
    network_mode: "host"
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/:/hostfs:ro"
      - "/var/log/collectd/:/var/log/collectd/"
    environment:
      - HOSTNAME=vb6
